#pragma once

#include "AuthCode.h"
#include "Base.h"
#include "BaseStream.h"
#include "event.h"
#include "face.h"
#include "regexMsg.h"
#include "StatusEvent.h"
#include "SystemGroupAdminEvent.h"
#include "Unpack.h"

#include "AnonymousInfo.h"
#include "BaseAPI.h"
#include "BasicEvent.h"
#include "code.h"
#include "GroupMemberInfo.h"
#include "LogStream.h"
#include "MsgSend.h"
#include "StrangerInfo.h"
#include "StrangerInfo.h"
#include "tool.h"

#include "API.h"
#include "FriendAddEvent.h"
#include "MsgEvent.h"
#include "RequestBasicEvent.h"

#include "DiscussMsgEvent.h"
#include "GroupMsgEvent.h"
#include "Logger.h"
#include "PrivateMsgEvent.h"
#include "RequestAddFriendEvent.h"
#include "RequestAddGroupEvent.h"
